services:
  - type: web
    name: apple-mug-detector
    env: docker
    plan: starter
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /health
    autoDeploy: true
