services:
  - type: web
    name: apple-mug-detector-v2-$(date +%s)
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python -u run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RENDER_CONFIG_VERSION
        value: "v2-$(date +%s)"
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "requirements.txt"
        - "wsgi.py"
        - "start.sh"
        - "start_app.py"
        - "run.py"
        - "app/**"
        - "templates/**"
        - "static/**"
        - "config.py"
        - "render.yaml"
