services:
  - type: web
    name: apple-mug-detector-v2
    env: python
    plan: starter
    buildCommand: |
      echo "=== BUILD STARTING ==="
      echo "Python version: $(python --version)"
      echo "Current directory: $(pwd)"
      echo "Files in directory: $(ls -la)"
      pip install -r requirements.txt
      echo "=== BUILD COMPLETED ==="
    startCommand: |
      echo "=== STARTING APPLICATION ==="
      echo "Using Python: $(which python)"
      echo "Current directory: $(pwd)"
      echo "Starting Flask app..."
      python start_app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RENDER_CONFIG_VERSION
        value: "v2-$(date +%s)"
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "requirements.txt"
        - "wsgi.py"
        - "start.sh"
        - "start_app.py"
        - "app/**"
        - "templates/**"
        - "static/**"
        - "config.py"
        - "render.yaml"
