services:
  - type: web
    name: apple-mug-detector
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /health
    autoDeploy: true
