services:
  - type: web
    name: apple-mug-detector
    env: docker
    plan: starter
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    buildCommand: docker build -f docker/Dockerfile -t apple-mug-detector .
    startCommand: gunicorn --bind 0.0.0.0:10000 --workers 1 --timeout 120 wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /health
    autoDeploy: true
